### define bearerAuth and studentId variables in http-client.private.env.json next to http-client.env.json

### get all student records
GET {{host}}/api/v1/students
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{bearerToken}}

### get basic student record from the service
GET {{host}}/api/v1/students/{{studentId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{bearerToken}}

### add basic student record to the service
POST {{host}}/api/v1/students
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{bearerToken}}

{
  "firstName": "Jane",
  "lastName": "Doe",
  "birthDate": "1950-11-29",
  "favoriteNumber": 28
}
