services:
  db:
    image: "docker-proxy.devops.projectronin.io/mysql/mysql-server:8.0"

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_pass"

  migrations:
    build:
        context: ronin-blueprint-database
        dockerfile: Dockerfile
    command: ["--url=jdbc:mysql://db/db", "--username=db_user", "--password=db_pass"]
    restart: on-failure

  service:
    build:
        context: ronin-blueprint-service
        dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/db
      - SPRING_DATASOURCE_USERNAME=db_user
      - SPRING_DATASOURCE_PASSWORD=db_pass
      - SEKI_URL=https://seki.dev.projectronin.io/
    ports:
      - 8080:8080
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/ping']
      interval: 30s
      timeout: 15s
      retries: 4
    depends_on:
      - db
      - migrations
    restart: on-failure
